# Make sure to check the documentation at http://goreleaser.com
# ---------------------------
# General
# ---------------------------
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^.github:'
      - '^test:'
      - '^graphs:'
      - '^history:'

# ---------------------------
# Builder
# ---------------------------
build:
  skip: true

# ---------------------------
# Github Release
# ---------------------------
release:
  prerelease: true
  name_template: "Release v{{.Version}}"
