# More information: https://upptime.js.org/docs/configuration

# Repo owner
owner: tonicpow
repo: status

# Assign incidents
assignees:
  - mrz1836

# Custom user agent
user-agent: TonicPow Status

# Skip build processes on readme
skipDescriptionUpdate: true

# Report on sites
sites:
  - name: TonicPow
    url: https://tonicpow.com
    icon: https://tonicpow.com/favicon-32x32.png
    maxResponseTime: 8000
    expectedStatusCodes:
      - 200
  - name: TonicPow API
      url: https://api.tonicpow.com
      icon: https://tonicpow.com/favicon-32x32.png
      maxResponseTime: 4000
      expectedStatusCodes:
        - 200
  - name: Tpow Link Service
    url: https://tpow.app
    icon: https://tonicpow.com/favicon-32x32.png
    maxResponseTime: 8000
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: GoBitcoinSV
    url: https://gobitcoinsv.com
    icon: https://gobitcoinsv.com/favicon.ico
    maxResponseTime: 8000
    expectedStatusCodes:
      - 200

# Status website configuration
status-website:
  theme: dark
  cname: status.tonicpow.com
  favicon: https://tonicpow.com/favicon-32x32.png
  logoUrl: https://tonicpow.com/images/tp_logo.svg
  name: TonicPow Status
  introTitle: "**System Status**"
  introMessage: View the live TonicPow network uptime, incidents and planned maintenance.
  customHeadHtml: "<!-- Custom HTML to add in the <head> tag -->"
  customBodyHtml: "<!-- Custom HTML to add at the beginning of <body> -->"
  navbar:
    - title: Status
      href: /
    - title: Contact
      href: https://tonicpow.com/#contact
    - title: Code
      href: https://github.com/$OWNER/$REPO

# Internationalization
i18n:
  footer: Back to [TonicPow](https://tonicpow.com)
