# More information: https://upptime.js.org/docs/configuration

# Repo owner
owner: tonicpow
repo: status

# Assign incidents
assignees:
  - mrz1836

# Custom user agent
user-agent: TonicPow Status v0.1.0

# Skip build processes on readme
skipDescriptionUpdate: true

# Schedule for all workflows
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Report on sites or endpoints
sites:
  - name: Website (Hosting)
    url: https://tonicpow.com
    icon: https://tonicpow.com/favicon-32x32.png
    maxResponseTime: 8000
    assignees:
      - mrz1836
    expectedStatusCodes:
      - 200
  - name: Website (Server)
    url: $WEB_SERVER_URL
    icon: https://tonicpow.com/favicon-32x32.png
    maxResponseTime: 4000
    assignees:
      - mrz1836
    expectedStatusCodes:
      - 200
  - name: API
    url: $API_URL
    icon: https://tonicpow.com/favicon-32x32.png
    maxResponseTime: 4000
    assignees:
      - mrz1836
    expectedStatusCodes:
      - 200
  - name: Short-Link Service
    url: $LINK_SERVICE_URL
    icon: https://tonicpow.com/favicon-32x32.png
    maxResponseTime: 4000
    assignees:
      - mrz1836
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: Documentation
    url: https://docs.tonicpow.com
    icon: https://tonicpow.com/favicon-32x32.png
    maxResponseTime: 8000
    assignees:
      - mrz1836
    expectedStatusCodes:
      - 200

# Status website configuration
status-website:
  theme: dark
  # themeUrl: https://status.tonicpow.com/custom-theme.css
  cname: status.tonicpow.com
  favicon: https://tonicpow.com/favicon-32x32.png
  logoUrl: https://tonicpow.com/images/tp_logo.svg
  name: TonicPow Status
  metaTags:
    - name: "application-name"
      content: "TonicPow Status"
    - name: "robots"
      content: "index, follow"
    - name: "description"
      content: "View the live TonicPow network uptime, incidents and planned maintenance. Contact support about issues, bugs or outages."
    - name: "keywords"
      content: "uptime, tonicpow, network, incidents, planned maintenance, support"
  introTitle: "**System Status**"
  introMessage: View the live TonicPow network uptime, incidents and planned maintenance.
  links:
    - rel: stylesheet
      #href: https://raw.githubusercontent.com/tonicpow/status/master/assets/custom-theme.css
      #href: https://rawcdn.githack.com/tonicpow/status/5d479334ab3304a93743aacae3d566fb05b96268/assets/custom-theme.css
      href: https://raw.githack.com/tonicpow/status/master/assets/custom-theme.css
  customHeadHtml: '
  <script>
    "use strict";
    !function() {
      var t = window.driftt = window.drift = window.driftt || [];
      if (!t.init) {
        if (t.invoked) return void (window.console && console.error && console.error("Drift snippet included twice."));
        t.invoked = !0, t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ],
        t.factory = function(e) {
          return function() {
            var n = Array.prototype.slice.call(arguments);
            return n.unshift(e), t.push(n), t;
          };
        }, t.methods.forEach(function(e) {
          t[e] = t.factory(e);
        }), t.load = function(t) {
          var e = 3e5, n = Math.ceil(new Date() / e) * e, o = document.createElement("script");
          o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + n + "/" + t + ".js";
          var i = document.getElementsByTagName("script")[0];
          i.parentNode.insertBefore(o, i);
        };
      }
    }();
    drift.SNIPPET_VERSION = "0.3.1";
    drift.load("ahmbhf2mwf2b");
  </script>
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-RG8TJ0TLGE"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag("js", new Date());
    gtag("config","G-RG8TJ0TLGE");
  </script>
  '
  customBodyHtml: "<!-- Custom HTML to add at the beginning of <body> -->"
  navbar:
    - title: Status
      href: /
    - title: Contact
      href: 'javascript:drift.api.openChat();'
    - title: Slack
      href: https://join.slack.com/t/tonicpow/shared_invite/zt-mlccqx28-IEabvOGPx_QLyFJJbWE3hQ

# Internationalization
i18n:
  footer: © 2021 [TonicPow](https://tonicpow.com/?utm_source=status_page&utm_medium=status_page&utm_campaign=footer&utm_term=footer&utm_content=footer), Inc. All rights reserved.
